[metasvr_conf]
bind_address = "0.0.0.0:8082"
keep_alive = 120
client_timeout = 3000
shutdown_timeout = 3
maxconn = 10000
maxconnrate = 2500
workers = 4
ssl = false

[db_pg_conf]
host = "192.168.31.31"
##port = 5433
##user = "yugabyte"
##password = "yugabyte"
port = 26257
user = "root"
password = "root"
dbname = "zz"
max_size = 100
min_idle = 10
idle_timeout = 3600
max_lifetime = 28800
connection_timeout = 5

[redis_conf]
host = "127.0.0.1"
port = 7777
passwd = "abcd.1234"
max_size = 100
min_idle = 10
idle_timeout = 3600
max_lifetime = 28800
connection_timeout = 5
